site_name: HUIT Academic Technology JupyterHub User Documentation

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - JupyterLab: jupyterlab.md

theme:
  name: material
  palette:
    scheme: harvard
  logo: assets/harvard_shield.svg
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
